# Generated by Django 3.2.12 on 2022-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220426_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_actived',
            field=models.BooleanField(default=False, help_text='Designates whether this user have activated his account. ', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name of User'),
        ),
    ]
